### PR TITLE
Development: Complete Milestone 5 and 6

### PR DESCRIPTION
**Pull request by oxenprogrammer**
# Milestone 5 and 6

## Project 1: Positioning and Floating Elements

_For this mini-project, we deconstruct an existing web page and rebuild it. using HTML5 and CSS3_
_Check the README.md file for more_
###  We used:
- Flexbox
- Positioning
##### Setup
- Clone or download the project and open it in your favorite text editor

#### Live link
- https://oxenprogrammer.github.io/new-york-times-clone/

top1
top2
top3
top4
top5
top6
top7

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @oxenprogrammer and @diamond-nicholas  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes]

- [ ] Remove the horizontal scrollbar line
- [ ] There is no footer, please add it
- [ ] The social media icons miss the surrounding grey circle
- [ ] The social media icons don't seem like the ones on the original page

| Your clone | Original page |
| --- | --- |
| Screenshot from 2020-11-26 07-06-10 | Screenshot from 2020-11-26 01-18-44 |


:point_right: Could you see the difference :question: :question: :question: 

- [ ] The newyork times icon you used in navbar is not the same as the one used on the original page, please use the one from the original page
- [ ] The picture caption of the large picture at the top, should be grey
- [ ] The license link you have in readme file doesn't work
- [ ] Fix the issue link you have in your readme file
- [ ] Using `flex` on this project is very good and encouraged since it is the main topic of it, but also we need you to learn and master how to use `float` and `grid`, currently there is no grid and no float in your CSS codes, try to use some
- [ ] You are using ID as CSS selectors, that is a bad practice

=======
If anything seems to be unclear to you, comment on this Pull Request and mention me as [@descholar-ceo](https://github.com/descholar-ceo)
 | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Comment by oxenprogrammer** [comment]
### Please clarify on the footer 
@descholar-ceo 

_Is it this?_

footer2

_or this?_

footer1

**Comment by descholar-ceo** [comment]
> ### Please clarify on the footer
> @descholar-ceo
> 
> _Is it this?_
> 
> footer2
> 
> _or this?_
> 
> footer1

Hello @oxenprogrammer, thank you for reaching out for more clarification. You should add the whole missing bottom part of the original page. Nothing should be left behind

**Review by Temmarie — CHANGES_REQUESTED** [review]
### Changes Required! :recycle:
Hi @oxenprogrammer and @diamond-nicholas  ! 👋 👋 👋 

### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

**Recommended**

- [ ] Fix the horizontal overflow. Adding a `overflow:hidden;` doesn't fix the problem. It only makes the page look tilted. Check out the "Theory of Inflation" section, the problem may lie there.

- [ ] Fix  the navigation bar in order to look as similar as possible to the NYT's site.

- [ ] Please fix the social media row, it remains just a little bit of an issue there.

 - [ ] Increase the font-size of the centralised text.

- [ ] Remove the excess side margins and adjust the page's positioning.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
Hello :wave: 

Some of the changes requested by the previous reviewer has not been made
- [ ] Your whole page seems to align more to the right side of the page. check the screenshot below to see how it appears on my screen and make changes accordingly.
Screenshot from 2020-11-27 19-02-48
- [ ] The social media link has still not been updated as it still does not look like the original.
- yours
Screenshot from 2020-11-27 19-11-08
- original
Screenshot from 2020-11-27 19-11-53
- [ ] The font size you used in the clone is too small and is making the articles section look smaller than it is in the original.
- yours
Screenshot from 2020-11-27 19-13-53
- original
Screenshot from 2020-11-27 19-14-32

Request another review when you are done making the changes

slack(@ebeagusamuel)

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @oxenprogrammer and @diamond-nicholas, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏  I appreciate your hard work in replicating nytimes.com.   Kindly fix the following issues.

[REQUIRED]

- [ ] The New York Times logo should a link
- [ ] Fix the read comments button and share icon style

| Your Copy | Source  |
| :---:         |     :---:      | 
|Screen Shot 2020-11-28 at 2 26 42 AM|Screen Shot 2020-11-28 at 2 26 56 AM|

- [ ] Don't repeat CSS rules create common utility classes for common CSS rules. E.g. 
```
.flex {
display: flex;
}
```

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Comment by oxenprogrammer** [comment]
I appreciate your PR review, however, I feel we are over reacting, especially for the repeated common utitlities, this is just week 1, getting to know HTML and CSS and not all properties and techniques have been learnt as yet. Sass, grid, and CSS frameworks are yet to be introduced. Go slow on us and focus on the essentials please.

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi team :wave: 

Great job so far . . .

However, the section of your web page the TSE pointed is still not looking good on my screen.

I guess you are working with a large screen. 

However, here are some pointers

- [ ] In your footer section, since you applied a flex-direction of column, to center your content, you have to use the **align-items: center** property.

Also, try to re-adjust the padding and margins for that section.

#### Make the changes then submit another form for a code review.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama```

**Review by Temmarie — CHANGES_REQUESTED** [review]
### Changes Required! :recycle:
Hi Team ! 👋 👋 

### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

#### As mentioned by the previous TSE, the page still looks tilted and just wrong overall. It is partly due to the fact that you have a horizontal overview which you used an `overflow:hidden;` to avoid.  Like I said earlier, you need to figure out the reason for the overflow in the first place.

**_If this is a result of differences in screen sizes, please let me know what screen size you are using._**


- [ ] Fix the footer . It looks scrambled.

Screenshot (99)

**Below are the way your project shows on my screen.**

Screenshot (101)


Screenshot (100)


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi Team! 👋 👋 

### Thank you for making all of the required changes and for reaching out to me regarding the difference in screen sizes, your project is approved :clap: :clap: :clap: :tada:

_**Please note, for future reference, do not open different Pull requests for a project submission unless required in Pathwright. Once you get a review, still submit the PR where the review was made so it's easy for the TSEs to see the previously required changes.**_

### You may merge, good luck with your next projects! :rocket:
### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by layzrd** [comment]
> I appreciate your PR review, however, I feel we are over reacting, especially for the repeated common utitlities, this is just week 1, getting to know HTML and CSS and not all properties and techniques have been learnt as yet. Sass, grid, and CSS frameworks are yet to be introduced. Go slow on us and focus on the essentials please.

Hi @oxenprogrammer , I am sorry if you get frustrated. We are here to learn and, writing clean code is essential in all projects so, kindly don't be discouraged. We are here to help you improve your skills.

Avoiding code duplication does not require knowing advanced stuff. In your code, you write `display: flex` 20 times and, it has many other duplications. I recommended you to use utility classes for the repeated CSS rules you used instead of writing the same CSS rule many times. 
You can do that with pure CSS with the same skill you already have. I think writing once is much easier than writing the same thing many times.

 See you at the top.

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Pull request merged**
